#ifndef PLACEHOLDER_VIDEO_HPP
#define PLACEHOLDER_VIDEO_HPP 1

#define PLACEHOLDER_VIDEO_FRAME_WIDTH 640
#define PLACEHOLDER_VIDEO_FRAME_HEIGHT 360
#define PLACEHOLDER_VIDEO_FRAMES_PER_SECOND 1
#define PLACEHOLDER_VIDEO_NUM_FRAMES 228

#define PLACEHOLDER_VIDEO_FILE "/initrd/FIFA_Arab_Cup_Qatar_2025TM_Offical_Song_Zamani.raw"

#endif