#define CONFIG_SCHED_USE_SAME_PML4 1
#define CONFIG_PS2K_INITIAL_BUF_SIZE 512
#define CONFIG_PS2K_DEBUG 1
#define CONFIG_PS2K_ALLOC_BUF_MALLOC 1
#define CONFIG_PS2K_ALLOC_BUF 1
#define CONFIG_ACPI_VERBOSE 1
